### ISSUE TITLE
Question about the cluster trajectory.

### ISSUE THREAD

**Issue by Cocoon-Ray** [hustvl/DiffusionDrive#21]
Hi, Thanks for your work. There is a puzzle for me. Could you please clarify this for more details. Thanks in advance.

My question is:

The cluster trajectory you get is only [x, y]，but the normalization function in the code norm_odo seems to contain the third dimension(heading), so what is the detail of it? Is the heading dimension computed before the trajectory tensor sending to the norm_odo  function, or the cluster process is also based on the heading dimension, and thus the anchor itself contains the heading dimension ?

**Comment by LegendBC** [comment]
> Hi, Thanks for your work. There is a puzzle for me. Could you please clarify this for more details. Thanks in advance.
> 
> My question is:
> 
> The cluster trajectory you get is only [x, y]，but the normalization function in the code norm_odo seems to contain the third dimension(heading), so what is the detail of it? Is the heading dimension computed before the trajectory tensor sending to the norm_odo function, or the cluster process is also based on the heading dimension, and thus the anchor itself contains the heading dimension ?

Hi @Cocoon-Ray , Thanks for your interest! This appears to be a legacy issue. You can safely ignore the normalization of the heading dimension since it is empty for `odo_info_fut[..., 2:3]` (i.e., the `odo_info_fut.shape` is `[...,2]`). Additionally, the clustering process does not depend on the heading dimension.
