### ISSUE TITLE
Request for the script to generate kmeans_navsim_traj_20.npy

### ISSUE THREAD

**Issue by sy121388** [hustvl/DiffusionDrive#9]
First off, congratulations on the great work and thank you for sharing your code with the community.

I'm looking to get DiffusionDrive up and running, and I see that it requires a file called kmeans_navsim_traj_20.npy. Would you be able to share the script you used to create this file? I'd really like to understand how it's generated. 

Thank you in advance for any help you can provide!

**Comment by LegendBC** [comment]
I mainly refer to SparseDrive [implementation](https://github.com/swc-17/SparseDrive/blob/main/tools/kmeans/kmeans_plan.py), but things change in NAVSIM. Since NAVSIM does not cache the annotation with a single file. So you need to first loop for the dataset to cache the annotation and then perform clustering. 

It may take me a while to reorganize my dirty implementation for better clarification and usage, you can implement it in your own way with the above reference.
